// Generates src/components/hero-pattern-data.ts: where each logo shape goes in
// the home page's hero. Run `bun run build:hero` after changing the settings
// below; the result is committed so every visitor sees the same pattern.
import { join } from "node:path"

import { logoGlyphs } from "@workspace/ui/lib/logo-glyphs"
import { scatter, seededRandom } from "@workspace/ui/lib/scatter"

const width = 1440
const height = 640
// Size of the shapes relative to the logo's own.
const scale = 0.48
// Space left between two shapes, in pixels.
const gap = 5
// Groups the sweep-in animation is split into, left to right, and its length.
const groups = 33
const sweep = 1.2
const seed = 20261005

const names = Object.keys(logoGlyphs) as (keyof typeof logoGlyphs)[]

// The radius of the circle, around its centre, that a shape fits in.
function radius(d: string) {
  const numbers = d.match(/-?\d+\.?\d*/g)!.map(Number)
  let max = 0
  for (let index = 0; index < numbers.length; index += 2) {
    max = Math.max(max, Math.hypot(numbers[index], numbers[index + 1]))
  }

  return max
}

// Shapes are placed by their centre and turned at any angle: keeping the
// centres two radii (plus the gap) apart means two shapes can never touch,
// whatever their rotation.
const largest = Math.max(...names.map((name) => radius(logoGlyphs[name])))
const minDistance = 2 * largest * scale + gap

const random = seededRandom(seed)
const points = scatter({ width, height, minDistance, random })

const columns = Array.from({ length: groups }, (_, index) => ({
  delay: Number(((index * sweep) / (groups - 1)).toFixed(3)),
  items: [] as { glyph: string; transform: string }[],
}))
for (const { x, y } of points) {
  const group = Math.min(
    Math.max(Math.floor((x / width) * groups), 0),
    groups - 1
  )
  columns[group].items.push({
    glyph: names[Math.floor(random() * names.length)],
    transform: `translate(${x.toFixed(1)} ${y.toFixed(1)}) rotate(${Math.floor(
      random() * 360
    )}) scale(${scale})`,
  })
}

await Bun.write(
  join(import.meta.dir, "../src/components/hero-pattern-data.ts"),
  `// Generated by scripts/build-hero-pattern.ts (\`bun run build:hero\`). Do not
// edit. The logo's three shapes scattered over a ${width}x${height} canvas, at
// least ${minDistance.toFixed(1)} px apart so they never overlap, in ${groups} groups that sweep in
// left to right.
import type { logoGlyphs } from "@workspace/ui/lib/logo-glyphs"

export const heroPatternColumns: {
  delay: number
  items: { glyph: keyof typeof logoGlyphs; transform: string }[]
}[] = ${JSON.stringify(columns)}
`
)
console.log(
  `${points.length} shapes, ${minDistance.toFixed(1)} px apart at least`
)
