// Generates src/components/download-qr-data.ts: the QR code of the beta
// download address, as an SVG path. Run with `bun run build:qr`.
import qrcode from "qrcode-generator"

import { betaDownloadUrl } from "../src/lib/links"

// Error correction "M": readable with up to 15 % of the code damaged.
const code = qrcode(0, "M")
code.addData(betaDownloadUrl)
code.make()

const size = code.getModuleCount()
// One rectangle per run of dark modules on a row.
let path = ""
for (let row = 0; row < size; row++) {
  for (let column = 0; column < size; column++) {
    if (!code.isDark(row, column)) {
      continue
    }
    const start = column
    while (column + 1 < size && code.isDark(row, column + 1)) {
      column++
    }
    path += `M${start} ${row}h${column - start + 1}v1h-${column - start + 1}z`
  }
}

await Bun.write(
  new URL("../src/components/download-qr-data.ts", import.meta.url),
  `// Generated by scripts/build-qr.ts — do not edit.
// QR code of ${betaDownloadUrl}

// Modules per side, without the quiet zone.
export const qrSize = ${size}

export const qrPath =
  "${path}"
`
)
console.log(`download-qr-data.ts written (${size}×${size} modules)`)
