// Generated by scripts/build-hero-pattern.ts (`bun run build:hero`). Do not
// edit. The logo's three shapes scattered over a 1440x640 canvas, at
// least 41.4 px apart so they never overlap, in 33 groups that sweep in
// left to right.
import type { logoGlyphs } from "@workspace/ui/lib/logo-glyphs"

export const heroPatternColumns: {
  delay: number
  items: { glyph: keyof typeof logoGlyphs; transform: string }[]
}[] = [
  {
    delay: 0,
    items: [
      {
        glyph: "peak",
        transform: "translate(40.1 422.7) rotate(64) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(25.9 494.6) rotate(38) scale(0.48)",
      },
      { glyph: "bar", transform: "translate(7.7 7.1) rotate(26) scale(0.48)" },
      {
        glyph: "wave",
        transform: "translate(-21.8 520.9) rotate(158) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(23.5 118.6) rotate(37) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(22.9 569.0) rotate(8) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(11.7 319.0) rotate(250) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-5.6 66.7) rotate(155) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(-12.5 280.5) rotate(229) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-26.2 457.6) rotate(36) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(12.5 165.9) rotate(316) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(-24.7 113.8) rotate(349) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(36.8 -40.5) rotate(3) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-3.7 358.3) rotate(66) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-34.0 160.7) rotate(347) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(5.1 218.5) rotate(92) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(-40.7 32.5) rotate(179) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(-4.0 408.5) rotate(53) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-23.2 -21.0) rotate(291) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(-40.1 317.5) rotate(55) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(34.1 619.4) rotate(47) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(-8.2 624.9) rotate(29) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(-33.7 236.5) rotate(260) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(-37.3 587.2) rotate(298) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(34.5 268.2) rotate(319) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(-5.3 675.3) rotate(55) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.037,
    items: [
      {
        glyph: "peak",
        transform: "translate(76.9 279.5) rotate(97) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(55.5 325.5) rotate(272) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(70.9 -2.5) rotate(173) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(65.5 92.5) rotate(268) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(48.8 48.0) rotate(128) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(44.9 378.5) rotate(291) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(50.1 217.2) rotate(6) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(66.4 543.6) rotate(306) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(68.1 142.7) rotate(100) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(56.8 461.0) rotate(214) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(83.6 633.2) rotate(124) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(66.6 671.9) rotate(99) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.075,
    items: [
      {
        glyph: "peak",
        transform: "translate(99.2 326.0) rotate(75) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(102.4 387.4) rotate(310) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(129.2 19.5) rotate(60) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(113.7 161.4) rotate(215) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(93.2 485.7) rotate(123) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(127.3 250.9) rotate(82) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(121.3 207.7) rotate(107) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(101.0 434.0) rotate(286) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(110.5 69.5) rotate(256) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(115.0 -37.4) rotate(278) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(108.3 535.1) rotate(67) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(109.3 675.2) rotate(357) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(91.5 584.3) rotate(56) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.112,
    items: [
      {
        glyph: "bar",
        transform: "translate(144.1 392.3) rotate(164) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(155.7 435.0) rotate(261) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(154.8 -19.0) rotate(116) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(138.4 495.1) rotate(250) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(136.9 101.5) rotate(136) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(160.4 295.1) rotate(284) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(161.0 342.5) rotate(348) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(169.9 177.1) rotate(194) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(135.0 590.4) rotate(127) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(148.4 642.1) rotate(260) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(155.7 533.7) rotate(186) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(170.1 679.2) rotate(265) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.15,
    items: [
      {
        glyph: "peak",
        transform: "translate(205.6 407.2) rotate(247) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(205.3 38.0) rotate(42) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(213.3 448.1) rotate(351) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(195.7 507.8) rotate(43) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(217.3 333.7) rotate(207) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(180.1 73.2) rotate(51) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(202.5 261.4) rotate(15) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(206.9 615.7) rotate(37) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(180.0 129.9) rotate(279) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(176.1 220.3) rotate(79) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(202.6 549.2) rotate(111) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(191.8 -40.1) rotate(266) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.188,
    items: [
      {
        glyph: "wave",
        transform: "translate(241.3 481.2) rotate(318) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(238.8 -25.6) rotate(283) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(255.1 30.9) rotate(350) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(231.9 99.5) rotate(33) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(248.7 363.1) rotate(128) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(239.0 571.0) rotate(173) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(246.3 279.7) rotate(311) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(232.4 229.7) rotate(152) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(222.6 657.4) rotate(68) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(223.6 176.2) rotate(68) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.225,
    items: [
      {
        glyph: "bar",
        transform: "translate(299.2 -23.0) rotate(264) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(271.0 430.1) rotate(326) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(290.0 492.1) rotate(114) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(287.9 382.1) rotate(232) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(282.6 121.4) rotate(116) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(289.3 540.1) rotate(7) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(294.2 314.7) rotate(81) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(290.0 240.4) rotate(234) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(279.1 619.9) rotate(110) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(265.4 73.5) rotate(200) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(272.0 184.7) rotate(54) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(273.5 665.9) rotate(103) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.263,
    items: [
      {
        glyph: "peak",
        transform: "translate(346.0 34.5) rotate(240) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(329.6 116.3) rotate(182) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(311.7 75.1) rotate(178) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(338.1 352.3) rotate(264) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(334.8 431.4) rotate(32) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(329.0 221.8) rotate(311) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(334.4 473.4) rotate(175) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(308.2 17.7) rotate(41) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(331.3 520.1) rotate(10) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(315.6 583.8) rotate(139) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(320.6 272.1) rotate(272) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(323.3 167.4) rotate(142) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(312.2 647.8) rotate(181) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.3,
    items: [
      {
        glyph: "peak",
        transform: "translate(387.1 113.2) rotate(74) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(368.3 70.8) rotate(2) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(374.8 -14.3) rotate(190) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(371.6 163.1) rotate(270) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(388.5 252.1) rotate(171) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(351.2 391.6) rotate(20) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(386.6 484.6) rotate(89) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(349.2 310.2) rotate(43) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(355.8 563.9) rotate(24) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(364.9 617.5) rotate(22) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(371.4 677.8) rotate(261) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.337,
    items: [
      {
        glyph: "bar",
        transform: "translate(415.1 151.0) rotate(275) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(395.5 36.3) rotate(109) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(431.4 -19.2) rotate(280) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(415.4 357.6) rotate(352) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(400.6 410.6) rotate(311) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(401.7 305.7) rotate(121) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(431.1 463.2) rotate(83) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(396.2 542.0) rotate(343) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(427.8 269.7) rotate(237) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(417.8 203.5) rotate(263) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(401.4 596.8) rotate(31) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(419.6 641.6) rotate(208) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.375,
    items: [
      {
        glyph: "bar",
        transform: "translate(464.5 127.9) rotate(39) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(443.3 89.4) rotate(68) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(459.5 219.6) rotate(128) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(460.3 16.4) rotate(30) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(459.6 302.6) rotate(335) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(459.6 394.8) rotate(195) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(463.9 351.9) rotate(246) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(444.3 542.8) rotate(154) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(469.7 261.8) rotate(265) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(457.8 590.8) rotate(114) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(474.9 504.7) rotate(87) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(476.1 631.1) rotate(106) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(447.5 672.6) rotate(253) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.412,
    items: [
      {
        glyph: "peak",
        transform: "translate(522.3 224.1) rotate(39) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(515.9 340.8) rotate(288) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(511.9 19.0) rotate(25) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(490.6 88.4) rotate(46) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(485.7 163.6) rotate(205) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(483.3 -20.3) rotate(150) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(482.7 461.6) rotate(231) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(520.3 505.1) rotate(242) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(503.3 398.1) rotate(69) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(497.7 546.7) rotate(53) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(494.6 671.3) rotate(81) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(505.1 592.9) rotate(295) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(520.2 638.3) rotate(42) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.45,
    items: [
      {
        glyph: "bar",
        transform: "translate(539.8 157.0) rotate(16) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(560.0 -35.4) rotate(242) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(528.7 273.8) rotate(224) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(537.9 59.3) rotate(297) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(542.5 384.9) rotate(162) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(524.0 115.7) rotate(107) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(529.8 435.2) rotate(156) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(560.4 490.9) rotate(314) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(542.9 547.4) rotate(194) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(548.6 597.1) rotate(102) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(559.9 661.2) rotate(280) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.487,
    items: [
      {
        glyph: "bar",
        transform: "translate(600.3 275.5) rotate(36) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(597.0 164.5) rotate(82) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(568.1 109.8) rotate(305) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(586.3 15.8) rotate(173) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(580.7 366.3) rotate(209) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(605.4 79.3) rotate(143) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(571.6 317.3) rotate(89) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(569.5 231.4) rotate(269) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(576.0 448.7) rotate(72) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(598.7 514.9) rotate(239) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(598.4 562.3) rotate(79) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(585.8 628.4) rotate(192) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.525,
    items: [
      {
        glyph: "bar",
        transform: "translate(639.7 260.2) rotate(148) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(651.6 311.0) rotate(268) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(636.9 29.7) rotate(99) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(650.2 168.2) rotate(286) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(615.1 -29.0) rotate(1) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(621.0 201.0) rotate(42) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(620.0 347.2) rotate(133) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(634.9 125.0) rotate(204) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(653.6 404.9) rotate(274) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(612.0 402.5) rotate(232) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(626.2 459.4) rotate(278) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(623.6 602.4) rotate(359) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(616.2 678.2) rotate(70) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.563,
    items: [
      {
        glyph: "peak",
        transform: "translate(691.8 301.0) rotate(345) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(684.7 248.7) rotate(348) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(691.2 382.3) rotate(120) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(678.8 96.0) rotate(80) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(693.9 181.3) rotate(72) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(663.2 -10.0) rotate(7) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(663.3 211.7) rotate(268) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(668.7 497.7) rotate(46) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(657.5 567.1) rotate(297) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(678.5 633.5) rotate(289) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(672.5 678.2) rotate(309) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.6,
    items: [
      {
        glyph: "peak",
        transform: "translate(738.6 72.9) rotate(307) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(740.8 337.5) rotate(281) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(730.0 -1.8) rotate(353) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(720.6 215.6) rotate(83) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(698.8 31.1) rotate(121) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(708.3 136.2) rotate(96) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(732.5 404.0) rotate(272) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(698.5 452.9) rotate(165) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(704.4 533.7) rotate(260) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(734.9 633.0) rotate(324) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(723.5 591.1) rotate(275) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(716.5 672.0) rotate(135) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.637,
    items: [
      {
        glyph: "bar",
        transform: "translate(747.1 152.0) rotate(224) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(764.3 201.6) rotate(324) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(778.3 -19.5) rotate(289) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(758.1 274.3) rotate(277) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(767.3 443.1) rotate(113) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(752.7 503.0) rotate(183) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(770.0 551.7) rotate(105) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(778.5 611.0) rotate(283) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.675,
    items: [
      {
        glyph: "bar",
        transform: "translate(822.8 151.1) rotate(168) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(794.1 114.6) rotate(85) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(816.8 79.0) rotate(204) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(786.5 49.5) rotate(142) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(788.7 239.8) rotate(277) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(792.9 296.6) rotate(146) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(791.8 386.0) rotate(48) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(812.6 335.3) rotate(329) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(822.4 -18.5) rotate(136) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(808.5 458.4) rotate(124) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(806.2 522.9) rotate(186) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(811.0 569.9) rotate(310) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(791.9 676.1) rotate(277) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.713,
    items: [
      {
        glyph: "peak",
        transform: "translate(832.1 200.5) rotate(39) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(861.5 108.4) rotate(130) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(866.9 -31.0) rotate(96) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(841.2 29.1) rotate(23) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(832.5 246.8) rotate(219) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(861.8 299.3) rotate(7) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(853.4 343.5) rotate(88) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(847.9 395.1) rotate(282) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(855.6 437.5) rotate(316) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(855.6 516.7) rotate(37) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(852.9 560.9) rotate(233) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(839.1 613.4) rotate(110) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(856.7 673.8) rotate(83) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.75,
    items: [
      {
        glyph: "bar",
        transform: "translate(894.7 141.0) rotate(168) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(886.5 189.5) rotate(128) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(888.8 59.6) rotate(301) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(897.4 5.4) rotate(219) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(910.2 234.5) rotate(109) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(875.0 257.7) rotate(129) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(912.2 428.1) rotate(13) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(878.8 481.7) rotate(259) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(914.2 540.7) rotate(6) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(901.5 645.1) rotate(28) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(880.0 597.0) rotate(42) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.787,
    items: [
      {
        glyph: "bar",
        transform: "translate(958.6 150.0) rotate(273) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(930.7 80.9) rotate(2) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(939.6 193.9) rotate(161) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(932.5 34.7) rotate(329) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(930.3 -38.5) rotate(336) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(935.7 270.6) rotate(288) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(927.4 330.8) rotate(56) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(925.0 379.2) rotate(98) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(924.7 486.6) rotate(226) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(928.0 595.7) rotate(309) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(949.1 670.1) rotate(319) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.825,
    items: [
      {
        glyph: "bar",
        transform: "translate(973.7 110.4) rotate(292) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(981.0 67.5) rotate(154) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(992.0 201.2) rotate(342) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(979.3 -15.1) rotate(99) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(973.7 26.6) rotate(208) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(975.3 248.4) rotate(71) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(972.2 292.1) rotate(245) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(977.8 386.3) rotate(92) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(981.9 344.9) rotate(116) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(978.8 461.3) rotate(216) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(971.0 548.2) rotate(65) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(973.9 611.8) rotate(348) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(981.8 503.2) rotate(80) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1002.5 664.6) rotate(148) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.862,
    items: [
      {
        glyph: "bar",
        transform: "translate(1040.3 70.3) rotate(73) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1014.7 129.6) rotate(297) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1034.6 175.8) rotate(322) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1044.6 10.4) rotate(286) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1025.2 290.5) rotate(137) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1026.4 -27.3) rotate(299) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1026.6 225.7) rotate(357) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1009.4 423.0) rotate(354) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1022.3 566.0) rotate(278) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.9,
    items: [
      {
        glyph: "peak",
        transform: "translate(1069.5 224.5) rotate(331) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1064.4 130.0) rotate(199) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1081.9 86.7) rotate(208) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1070.5 -32.3) rotate(89) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1047.7 337.0) rotate(297) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1090.0 336.5) rotate(43) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1048.0 389.4) rotate(9) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1061.1 266.1) rotate(217) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1090.9 407.6) rotate(60) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1089.5 480.6) rotate(338) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1048.8 466.3) rotate(77) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1054.3 535.5) rotate(284) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1050.1 627.2) rotate(180) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1080.1 175.8) rotate(60) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1065.2 581.7) rotate(213) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1062.9 679.4) rotate(320) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.938,
    items: [
      {
        glyph: "wave",
        transform: "translate(1104.8 52.1) rotate(289) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1121.3 -11.9) rotate(66) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1121.5 123.3) rotate(29) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1117.4 194.8) rotate(319) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1097.2 291.3) rotate(358) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1127.7 355.4) rotate(186) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1109.1 248.1) rotate(316) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1114.7 561.0) rotate(89) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1129.8 512.3) rotate(205) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1108.5 635.7) rotate(186) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1117.1 678.0) rotate(202) scale(0.48)",
      },
    ],
  },
  {
    delay: 0.975,
    items: [
      {
        glyph: "peak",
        transform: "translate(1147.1 49.5) rotate(315) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1162.6 164.0) rotate(343) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1162.3 101.0) rotate(92) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1157.7 -40.8) rotate(116) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1152.9 309.6) rotate(149) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1145.1 423.2) rotate(103) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1176.1 261.6) rotate(327) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1154.0 223.5) rotate(118) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1172.5 374.6) rotate(284) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1154.8 472.4) rotate(110) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1172.2 524.5) rotate(128) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1166.3 567.6) rotate(9) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1159.2 617.6) rotate(257) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1166.2 680.0) rotate(147) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.012,
    items: [
      {
        glyph: "bar",
        transform: "translate(1192.4 1.9) rotate(218) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1199.1 124.6) rotate(139) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1188.2 66.6) rotate(212) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1193.1 205.1) rotate(312) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1195.1 334.1) rotate(145) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1211.7 391.1) rotate(352) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1207.6 460.6) rotate(254) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1215.3 669.5) rotate(131) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1203.6 601.4) rotate(276) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.05,
    items: [
      {
        glyph: "wave",
        transform: "translate(1239.1 19.3) rotate(155) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1231.6 88.6) rotate(251) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1238.2 166.0) rotate(67) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1228.2 -40.8) rotate(105) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1235.3 246.4) rotate(286) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1248.5 430.8) rotate(85) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1228.1 287.2) rotate(22) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1230.2 504.8) rotate(19) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1229.5 551.9) rotate(287) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1232.8 353.3) rotate(35) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1251.9 602.5) rotate(169) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.087,
    items: [
      {
        glyph: "peak",
        transform: "translate(1271.9 205.1) rotate(346) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1281.0 147.8) rotate(236) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1278.6 -19.3) rotate(252) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1276.1 506.1) rotate(345) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1279.5 78.3) rotate(48) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1275.4 342.9) rotate(234) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1280.5 289.6) rotate(175) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1298.0 570.9) rotate(276) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1288.9 401.7) rotate(63) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1308.6 462.2) rotate(82) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1280.3 247.9) rotate(198) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1269.2 641.7) rotate(281) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1304.4 671.2) rotate(141) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.125,
    items: [
      {
        glyph: "wave",
        transform: "translate(1325.0 -27.1) rotate(212) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1313.3 27.7) rotate(250) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1312.0 176.6) rotate(262) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1319.0 94.9) rotate(329) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1352.7 208.6) rotate(45) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1345.8 325.7) rotate(269) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1329.0 270.3) rotate(35) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1352.0 519.8) rotate(269) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1313.5 366.3) rotate(324) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1316.2 630.9) rotate(262) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1311.2 219.4) rotate(184) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.162,
    items: [
      {
        glyph: "bar",
        transform: "translate(1358.7 33.6) rotate(89) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1372.8 -15.9) rotate(179) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1386.9 77.8) rotate(217) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1385.6 120.2) rotate(245) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1365.4 160.8) rotate(340) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1373.3 286.8) rotate(291) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1379.8 386.1) rotate(162) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1371.4 572.1) rotate(130) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1391.5 338.9) rotate(20) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1353.9 423.3) rotate(241) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1377.9 466.1) rotate(304) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1382.5 661.8) rotate(170) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1358.7 626.6) rotate(259) scale(0.48)",
      },
    ],
  },
  {
    delay: 1.2,
    items: [
      {
        glyph: "bar",
        transform: "translate(1415.2 -11.6) rotate(34) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1452.3 85.2) rotate(187) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1447.1 141.3) rotate(348) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1422.6 183.4) rotate(170) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1468.7 7.9) rotate(149) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1406.0 258.3) rotate(288) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1479.7 182.8) rotate(68) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1433.9 43.0) rotate(185) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1479.0 234.7) rotate(149) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1427.2 307.9) rotate(280) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1459.7 274.5) rotate(117) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1426.2 373.2) rotate(159) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1465.5 342.6) rotate(115) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1424.5 448.0) rotate(187) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1478.2 396.4) rotate(350) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1454.2 494.5) rotate(129) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1418.4 516.2) rotate(267) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1439.7 609.4) rotate(268) scale(0.48)",
      },
      {
        glyph: "peak",
        transform: "translate(1397.8 612.4) rotate(212) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1457.6 566.2) rotate(81) scale(0.48)",
      },
      {
        glyph: "bar",
        transform: "translate(1457.1 664.9) rotate(96) scale(0.48)",
      },
      {
        glyph: "wave",
        transform: "translate(1416.0 574.9) rotate(0) scale(0.48)",
      },
    ],
  },
]
