// Generates src/map-view/html.ts: the self-contained page shown in the map's web view, with
// Leaflet, Supercluster and page.js inlined so it needs no bundler support and
// no CDN at run time. Run `bun run build:map` after changing page.js or
// upgrading Leaflet.
import { dirname, join } from "node:path"

import { ideogram } from "@workspace/ui/lib/logo-glyphs"
import { lightColors as colors } from "@workspace/ui/native/tokens"

const mapView = join(import.meta.dir, "../src/map-view")
// Leaflet's entry point is node_modules/leaflet/dist/leaflet-src.js.
const nodeModules = join(
  dirname(Bun.resolveSync("leaflet", import.meta.dir)),
  "../.."
)
const read = (path: string) => Bun.file(join(nodeModules, path)).text()

// Leaflet's stylesheet minus the rules that load images (layer switcher and
// default marker), which this map does not use.
const leafletCss = (await read("leaflet/dist/leaflet.css"))
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/[^{}]+\{[^{}]*url\([^{}]*\}/g, "")

const css = `
html, body, #map { position: absolute; inset: 0; margin: 0; }
body { background: ${colors.muted}; font-family: system-ui, sans-serif; }
.pin { box-sizing: border-box; width: 100%; height: 100%; border-radius: 50%;
  border: 3px solid #fff; background: #fff; box-shadow: 0 1px 4px rgba(53, 61, 77, .35); }
.pin.selected { outline: 4px solid ${colors.slate}; }
.picker { position: absolute; left: 50%; top: 50%; z-index: 1000; width: 52px; height: 52px;
  margin: -26px 0 0 -26px; pointer-events: none; }
.cluster { box-sizing: border-box; display: grid; place-items: center; width: 100%; height: 100%;
  border-radius: 50%; border: 6px solid rgba(53, 61, 77, .25); background: ${colors.slate};
  background-clip: padding-box; color: #fff; font-weight: 700; font-size: 14px; }
.position { display: grid; place-items: center; width: 100%; height: 100%; border-radius: 50%;
  background: rgba(0, 150, 222, .18); }
.position div { box-sizing: border-box; width: 20px; height: 20px; border-radius: 50%;
  border: 3px solid #fff; background: ${colors.blue}; box-shadow: 0 1px 4px rgba(53, 61, 77, .35); }
`

const config = { ideogram, blue: colors.blue, blueText: colors.blueText }
const scripts = [
  await read("leaflet/dist/leaflet.js"),
  await read("supercluster/dist/supercluster.min.js"),
  `var CONFIG = ${JSON.stringify(config)};`,
  await Bun.file(join(mapView, "page.js")).text(),
]

const html = `<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<style>${leafletCss}${css}</style>
</head>
<body>
<div id="map"></div>
${scripts.map((script) => `<script>${script.replace(/<\/script/gi, "<\\/script")}</script>`).join("\n")}
</body>
</html>
`

await Bun.write(
  join(mapView, "html.ts"),
  `// Generated by scripts/build-map-html.ts (\`bun run build:map\`). Do not edit.\nexport const mapHtml = ${JSON.stringify(html)}\n`
)
console.log(`html.ts written (${Math.round(html.length / 1024)} KB)`)
